language: python
python:

  - "2.7"
  - "3.4"
  - "3.5"

# command to install dependencies
install:
  - cat system_requirements.txt | xargs sudo apt-get install
  - pip install -r python_requirements.txt
  - pip install coveralls

script:

  - coverage run --omit=*.virtualenvs*,*virtualenv* code/lip_tracking/VisualizeLip.py test

after_success:
  coveralls

sudo: enabled
dist: trusty
